Cargo.toml, linux-version/Cargo.toml, userfaultfd-sys/Cargo.toml
Updates the Cargo.toml files to specify version for dependent local crates.
Also adds some details to the Cargo.toml of the top level package.
=> Prepare for release to crates.io

CHANGELOG.md, Cargo.lock, Cargo.toml, linux-version/Cargo.toml, userfaultfd-sys/Cargo.toml
This is the initial public release of userfaultfd-rs. 
I'm roughly following the same [release style](https://bytecodealliance.github.io/lucet/versioning_releasing.html) that we do for Lucet. So, once this gets approval, I will do the following:
* Release to crates.io
* Tag the release
* Bump packages to 0.2.0-dev
* Merge this PR
=> Release 0.1.0

Cargo.toml, userfaultfd-sys/Cargo.toml
Attempting to consume this package from one which uses a later version of bindgen, and it seems like the differing version of clang-sys dependencies don't play nicely together. Not entirely sure why possibly/probably due to linking against the system libclang library?... Assuming we need to bump the version of bindgen.
This is the error:
```
cargo build \
--release \
--target="aarch64-unknown-linux-musl" \
--manifest-path="memory-manager/Cargo.toml" \
--target-dir="/workplace/jgowans/build-aarch64/memory-manager"
Updating crates.io index
error: failed to select a version for `clang-sys`.
... required by package `bindgen v0.56.0`
... which is depended on by `memory-manager v0.1.0 (/workplace/jgowans/memory-manager/memory-manager)`
versions that meet the requirements `>=1.0.0, <2.0.0` are: …
```
=> Bump bindgen version

CHANGELOG.md, src/error.rs, src/lib.rs
This commit implements `Uffd::read_events` that users can call to read multiple
events into a caller-supplied buffer.
An iterator is returned that reads the `Event` objects out of the buffer for
the events that were read.
The implementation of `read_event` was updated as a call to `read_events`,
supplying a buffer large enough for a single event.
Three tests were added: `read_event`, `nonblocking_read_event`, and `read_events`.
The `read_events` test is inherently racy, but is implemented to help minimize
hitting the race condition.
=> Implement `Uffd::read_events`.

src/lib.rs
read(2) returns 0 on EOF, rather than `libc::EOF`.
This also matches the EOF check done in the userfaultfd [example].
[example]: https://man7.org/linux/man-pages/man2/userfaultfd.2.html#EXAMPLES
I haven't observed EOF on a userfaultfd occurring in an actual use; this is
just something I noticed while reading the code.
=> Check for the correct EOF value from read(2).

Cargo.toml
No code changes since release 0.3.3. However, 0.3.3 was semver-incompatible with 0.3.2, so we need to publish it as 0.4.0 and then yank 0.3.3.
Fixes #23
=> userfaultfd: update version to 0.4.0

.github/workflows/rust.yml, Cargo.toml, examples/manpage.rs, linux-version/Cargo.toml, src/builder.rs, src/lib.rs, tests/manpage_example.rs, userfaultfd-sys/wrapper.h
=> Add builder flag to use user-mode only userfaultfd

Cargo.toml, userfaultfd-sys/Cargo.toml
userfaultfd-sys goes from 0.3.1 -> 0.4.0: minor bump is required
userfaultfd goes from 0.4.1 -> 0.4.2: builder adds an additional method, so only patch bump is required
=> release 0.4.2

userfaultfd-sys/src/consts.c, userfaultfd-sys/src/linux4_11.rs, userfaultfd-sys/src/linux4_14.rs, userfaultfd-sys/src/linux5_7.rs
Define `UFFDIO_COPY_MODE_WP`, similar to `UFFDIO_COPY_MODE_DONTWAKE`.
And define the `UFFDIO_*` ioctl request code macros.
As with other constants in userfaultfd-sys, this hard-codes magic
numbers for these constants, and adds tests to check their values
against the values seen by C.
=> Define `UFFDIO_COPY_MODE_WP`, and the `UFFDIO_*` ioctl constants.

userfaultfd-sys/Cargo.toml
only addition is 682a29ba78b9e2df8189fad1586bc11a771fdd5a, which adds additional constants.
=> bump userfaultfd-sys to 0.4.1

userfaultfd-sys/Cargo.toml
`cargo test` on userfaultfd-sys fails due to compile error: reference to packed field is unaligned. The error was introduced recently (https://github.com/rust-lang/rust/issues/82523) and the latest bindgen supports it.
```
$ cargo -V
cargo 1.65.0-nightly (6da726708 2022-08-23)
```
=> Update bindgen to the latest (0.60.1)

userfaultfd-sys/Cargo.toml
This also match the version of cfg-if between userfaultfd and userfaultfd-sys packages.
=> Update cfg-if to the latest (1.0.0)

Cargo.toml
This adds an enum variant to `Error`, so its a minor version bump.
Changelog since 0.4.2:
#29 Define UFFDIO_COPY_MODE_WP, and the UFFDIO_* ioctl constants
#34 Update bindgen to the latest (0.60.1)
#35 Update cfg-if to the latest (1.0.0) 
#36 Add PartiallyCopied error for copy() 
#33 Fix linux4_14 feature flags
=> release userfaultfd 0.5.0

userfaultfd-sys/Cargo.toml
This is a patch release, the only changes are to deps which do not change the public API:
#35 upgrades cfg-if to 1.0.0
#34 upgrades bindgen to 0.60.1
This should have been done as part of #37 but I missed it.
=> userfaultfd-sys: release 0.4.2

.github/workflows/rust.yml
ubuntu-latest image upgraded to 22.04 since last run. this means its running on kernel 5.15, so the included headers should be new enough to build the 5.7 feature.
=> ci: no need to install later linux-headers anymore

Cargo.toml, userfaultfd-sys/Cargo.toml
userfaultfd-sys just had the repo metadata updated userfaultfd had the repo metadata, plus upgrade to nix 0.26 https://github.com/bytecodealliance/userfaultfd-rs/pull/41
=> patch version bump of both crates for release

userfaultfd-sys/Cargo.toml
userfaultfd-sys fails to build <linux/userfaultfd.h> header file with newer clang. Newer bindgen have fix for it
https://github.com/rust-lang/rust-bindgen/pull/2319
=> Update bindgen to the latest (0.65.1)

userfaultfd-sys/Cargo.toml
The update does not change the public interface.
PR #44 Update bindgen to the latest (0.65.1)
=> userfaultfd-sys: release 0.4.4

CHANGELOG.md, Cargo.toml, src/builder.rs, src/lib.rs
bitflags no longer automatically derives traits so we need to explicitly derive them.
=> Update bitflags to 2.2.1.

Cargo.toml
The diff from 0.5.1 is a major version bump of the bitflags dep: https://github.com/bytecodealliance/userfaultfd-rs/pull/47
Since bitflags is a proc-macro which generates public impls in the userfaultfd crate, we are treating this update as breaking compatibility, hence bumping the minor 0.x version.
=> bump userfaultfd crate version to 0.6.0

.github/workflows/rust.yml
It looks as if when we opened #56 `ubuntu-latest` Github Actions runner image did not ship a kernel that was >= 6.1. So, the code that created the userfault file descriptor did not use the ioctl to `/dev/userfaultfd` path and it always succeeded (using the `userfaultfd` syscall).
It seems that at some point afterwards `ubuntu-latest` came with an update kernel (6.2) and it triggered the `/dev/userfaultfd` path. As a result, the test fails on `main` and subsequent PRs (#57) because the Github actions job runs as the user `runner` which doesn't have access to read/write `/dev/userfaultfd`.
This PR fixes this situation doing two things:
1. It runs the tests both in `ubuntu-latest`, with kernel 6.2 and `ubuntu-20.04`, with kernel 5.15 to exercise both paths.
2. In the case of `ubuntu-latest`, …
=> Fix failure in Github action

examples/manpage.rs
I found the output of the `manpage` example regarding the `POLLIN` event quite confusing. It ought to be true. But it is false because the `pollfd` is copied mistakenly.
```shell
$ cargo run --example manpage -- 1
...
fault_handler_thread():
poll() returns: nready = 1; POLLIN = false; POLLERR = false
...
```
=> Fix the manpage example

Cargo.toml, src/builder.rs, src/error.rs, src/lib.rs
This is the mitigation for #61. 
Returning Error::UnrecognizedIoctls is inconvinient for developers because the only way to solve it is modifying this userfaultfd-rs crate implementation.
For example, Linux v6.6 adds UFFDIO_POISON bit to
uffdio_register.iotcls. With that change, Uffd::register() always fails even if the user don't care about the new UFFDIO_POISON feature.
We need to guard this change behind the ignore_unknown_ioctlflags feature because Error::UnrecognizedIoctls is already published and some user may depend on the error.
Using an unnamed flag for externally defined flag is originally recommended.
https://docs.rs/bitflags/latest/bitflags/#externally-defined-flags
=> Make IoctlFlags robust to unknown flags

Cargo.toml
unnamed flags is supported from bitflags `2.4.0`. IoctlFlags started to use the unnamed flag from userfaultfd `0.8.0`.
This is a minor bug fix for #62
=> Update bitflags required version
